#!/usr/bin/env bash
# ┌┐ ┌─┐┌─┐┬ ┬┌┬┐┬─┐┌─┐
# ├┴┐└─┐├─┘││││││├┬┘│ 
# └─┘└─┘┴  └┴┘┴ ┴┴└─└─┘
#   (Font: ANSI - Calvin S 14pt)
#
# - By: drovoh4k

read -r RICETHEME < "$HOME"/.config/bspwm/.rice
export RICETHEME
PATH="$HOME/.config/bspwm/scripts:$PATH"
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1


# ┬ ┬┌─┐┬─┐┬┌─┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐
# ││││ │├┬┘├┴┐└─┐├─┘├─┤│  ├┤ └─┐
# └┴┘└─┘┴└─┴ ┴└─┘┴  ┴ ┴└─┘└─┘└─┘

# Default 1 monitor with 10 workspaces

# Default 1 monitor with 6 workspaces
for monitor in "$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"; do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7' '9' '9' '10'
done

## For two or three monitors configuration see https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup


# ┌┐ ┌─┐┌─┐┬ ┬┌┬┐  ┌─┐┌─┐┌┐┌┌─┐┬┌─┐
# ├┴┐└─┐├─┘││││││  │  │ ││││├┤ ││ ┬
# └─┘└─┘┴  └┴┘┴ ┴  └─┘└─┘┘└┘└  ┴└─┘

bspc config window_gap                  6
bspc config split_ratio                 0.51
bspc config single_monocle              true
bspc config borderless_monocle          false
bspc config gapless_monocle             false

bspc config focus_follows_pointer       false
bspc config pointer_follows_focus       false
bspc config pointer_motion_interval     5
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on


# ┌─┐┬ ┬┌┬┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌┬┐
# ├─┤│ │ │ │ │└─┐ │ ├─┤├┬┘ │ 
# ┴ ┴└─┘ ┴ └─┘└─┘ ┴ ┴ ┴┴└─ ┴ 

# Terminate already running polybar and sxhkd instances
processes=("polybar" "sxhkd")
    for process in "${processes[@]}"; do
        if pgrep -f "$process"; then
            pkill -9 -f "$process" > /dev/null; sleep 0.1
        fi
    done

# Load bspwm conf, colors and bars
. ${rice_dir}/Theme.sh

# Launch picom // If you have old hardware or encounter problems 
# uncomment the picom "--legacy-backends" line and comment the current one.
pgrep -x picom > /dev/null || { picom --config "$HOME"/.config/bspwm/picom.conf & }
#pidof -q picom || { picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf & }

# Set wallpaper for actual rice
feh -z --no-fehbg --bg-fill ${rice_dir}/wallpapers

# Reload sxhkd daemon
pgrep -x sxhkd > /dev/null || { sxhkd -c "$HOME"/.config/bspwm/sxhkdrc & }

# Allow clipboard sharing
vmware-user-suid-wrapper &

# Fix cursor
xsetroot -cursor_name left_ptr
