#!/bin/env bash

ids=($(bspc query -N -n .hidden.window))
(( "${#ids[@]}" )) || exit
for wid in "${ids[@]}"; do
    # title="$(xtitle "$wid")"
    title="$(xprop -id "$wid" WM_NAME | cut -d\" -f 2)"
    options+="${title:-"$(bspc query -T -n "$wid" | jq -r '
        .client | "\(.instanceName):\(.className)"
    ')"}"$'\n'
done

id_index="$(<<< "$options" rofi -dmenu -i -format i -p "Show" -theme $HOME/.config/bspwm/rices/hacking/scripts/rofi/launcher.rasi -dpi 200)"
bspc node "${ids[${id_index}]}" -g hidden=off -f; bspc node "${ids[${id_index}]}" -g sticky=off -f
